version: "3.9"


services:
  fastapi-service-1:
    container_name: "fastapi-service-1"
    build: "./fastapi-service"
    restart: "always"
  nginx:
    image: "nginx:latest"
    restart: always
    ports:
      - "10000:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
